wandb_version: 1

epochs:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716171852
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 7
      - 8
      - 16
      - 23
      - 38
      4: 3.11.4
      5: 0.17.0
      8:
      - 1
      - 3
      - 5
      10:
      - 9
      13: windows-amd64
    m:
    - 1: epoch/epoch
      6:
      - 3
    - 1: epoch/loss
      5: 1
      6:
      - 1
    - 1: epoch/val_loss
      5: 1
      6:
      - 1
